# -*- coding: utf-8 -*-
"""numpy(10).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nbuzaGlFcWydiAMpddBmbi_uzivETdJs
"""

import numpy as np

"""#10"""

#10
arr = np.zeros((5,5), int)
arr

np.fill_diagonal(arr, 1)
arr

"""#4"""

#4
bar = np.array([[[5, -15, 15, 20],
                 [25, -30, 35, 40],
                 [45,  50, -7, -60]]])
bar

bar[bar < 0] = 0
bar

"""#5"""

arr2 = np.array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

arr3 = np.array([[0, 53, 10],
       [2, 9, -3],
       [1, 15, 24]])

arr2.put([1, 3, 5], arr3)

arr2

"""#6"""

arr4 = np.array([[1, 2, 0],
                 [0, 5, 6],
                 [7, 0, 9]])

index = np.argwhere(arr4 == 0)

index #індекси нульових елементів

"""#7"""

arr5 = np.array([[ 1,  0,  3],
                 [53,  5, 10],
                 [ 7,  8,  9]])

rows = arr5[[1]]

rows #Другий рядок(перший за порядком)

"""#9"""

arr6 = np.array([[ 1,  0,  3],
                 [53,  5, 10],
                 [ 7,  8,  9]])

rownumb  = np.where(np.any(arr6 > 7, axis = 1)) #Візьмемо число 7 за x

rownumb #номери рядків які містять числа > x(7)